
INSERT 
  /*+  APPEND PARALLEL  */ 
  INTO ODI_USER.ORA_CUSTOMER
  (
    CUST_ID ,
    RANK ,
    GENDER ,
    CUST_NAME ,
    ADDRESS ,
    PREFECTURE ,
    PHONE ,
    AGE ,
    AGE_RANGE ,
    SALES_PERS ,
    CRE_DATE ,
    UPD_DATE 
  ) 
SELECT 
  INLINE_VIEW.CUSTID ,
  INLINE_VIEW.RANK ,
  case when INLINE_VIEW.TITLE = '0' then 'men'
when INLINE_VIEW.TITLE = '1' THEN 'women'
else 'others'
end ,
  INLINE_VIEW.LAST_NAME || INLINE_VIEW.FIRST_NAME ,
  INLINE_VIEW.ADDRESS ,
  INLINE_VIEW.PREFECTURE ,
  INLINE_VIEW.PHONE ,
  INLINE_VIEW.AGE ,
  F_AGE_GROUP_A.RANGE ,
  INLINE_VIEW.SALES_REPS ,
  SYSDATE ,
  SYSDATE  
FROM 
  (
SELECT 
  F_CUSTOMER_A.CUSTID AS CUSTID ,
  F_CUSTOMER_A.RANK AS RANK ,
  F_CUSTOMER_A.LAST_NAME AS LAST_NAME ,
  F_CUSTOMER_A.FIRST_NAME AS FIRST_NAME ,
  F_CUSTOMER_A.SALES_ID AS SALES_ID ,
  F_CUSTOMER_A.PREFECTURE AS PREFECTURE ,
  F_CUSTOMER_A.TITLE AS TITLE ,
  F_CUSTOMER_A.ADDRESS AS ADDRESS ,
  F_CUSTOMER_A.PHONE AS PHONE ,
  ORA_SALES.SALES_ID AS SALES_ID_1 ,
  ORA_SALES.OFFICE AS OFFICE ,
  ORA_SALES.SALES_REPS AS SALES_REPS ,
  ORA_SALES.AGE AS AGE   
FROM 
  ODI_USER.C F_CUSTOMER_A  INNER JOIN  ODI_USER.ORA_SALES ORA_SALES  
    ON  F_CUSTOMER_A.SALES_ID = ORA_SALES.SALES_ID
WHERE
  (ORA_SALES.OFFICE = 'HQ'
) 
  ) INLINE_VIEW  LEFT OUTER JOIN  ODI_USER.C F_AGE_GROUP_A  
    ON  INLINE_VIEW.AGE between F_AGE_GROUP_A.MIN and F_AGE_GROUP_A.MAX
    ;
