create table ODI_USER.test_ext
(
SALES_NONUMBER(12,0),
OFFICEVARCHAR2(50),
LAST_NAMEVARCHAR2(50),
FIRST_NAMEVARCHAR2(50),
HIRE_DATEVARCHAR2(50),
AGENUMBER(12,0)
)
ORGANIZATION EXTERNAL
(
TYPE ORACLE_LOADER
DEFAULT DIRECTORY dat_dir
ACCESS PARAMETERS
(
RECORDS DELIMITED BY 0x'0D0A'
CHARACTERSET 'AL32UTF8'
STRING SIZES ARE IN CHARACTERS
BADFILE'F_SALES_%a.bad'
LOGFILE'F_SALES_%a.log'
DISCARDFILE'F_SALES_%a.dsc'
SKIP 1
FIELDS  TERMINATED BY  x'3B'
MISSING FIELD VALUES ARE NULL 
(
SALES_NO,
OFFICECHAR(50),
LAST_NAMECHAR(50),
FIRST_NAMECHAR(50),
HIRE_DATECHAR(50),
AGE
)
        )
LOCATION ('basic/files/F_SALES_utf8.txt')
)
