 CREATE TABLE CUSTOMER  (
CUST_ID VARCHAR(30) NOT NULL, 
RANK VARCHAR(2), 
GENDER VARCHAR(50), 
CUST_NAME VARCHAR(100), 
ADDRESS VARCHAR(100), 
PREFECTURE VARCHAR(50), 
PHONE VARCHAR(50), 
AGE VARCHAR(10), 
AGE_RANGE VARCHAR(50), 
SALES_PERS VARCHAR(100), 
CRE_DATE VARCHAR(30), 
UPD_DATE VARCHAR(30) 
);
